-- MySQL Script generated by MySQL Workbench
-- Tue Oct 13 15:12:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema almoxarifadoWeb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema almoxarifadoWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `almoxarifadoWeb` DEFAULT CHARACTER SET utf8 ;
USE `almoxarifadoWeb` ;

-- -----------------------------------------------------
-- Table `almoxarifadoWeb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifadoWeb`.`tb_produto` (
  `codigo` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almoxarifadoWeb`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifadoWeb`.`tb_funcionario` (
  `codigo` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almoxarifadoWeb`.`tb_item_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifadoWeb`.`tb_item_estoque` (
  `codigo` INT NOT NULL auto_increment,
  `quantidade` INT NULL,
  `tb_produto_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_tb_item_estoque_tb_produto_idx` (`tb_produto_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_item_estoque_tb_produto`
    FOREIGN KEY (`tb_produto_codigo`)
    REFERENCES `almoxarifadoWeb`.`tb_produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almoxarifadoWeb`.`tb_lote_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifadoWeb`.`tb_lote_entrada` (
  `codigo` INT NOT NULL auto_increment,
  `data` DATE NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almoxarifadoWeb`.`tb_item_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifadoWeb`.`tb_item_entrada` (
  `codigo` INT NOT NULL auto_increment,
  `quantidade` INT NULL,
  `tb_produto_codigo` INT NOT NULL,
  `tb_lote_entrada_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `tb_lote_entrada_codigo`),
  INDEX `fk_tb_item_entrada_tb_produto1_idx` (`tb_produto_codigo` ASC) VISIBLE,
  INDEX `fk_tb_item_entrada_tb_lote_entrada1_idx` (`tb_lote_entrada_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_item_entrada_tb_produto1`
    FOREIGN KEY (`tb_produto_codigo`)
    REFERENCES `almoxarifadoWeb`.`tb_produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_item_entrada_tb_lote_entrada1`
    FOREIGN KEY (`tb_lote_entrada_codigo`)
    REFERENCES `almoxarifadoWeb`.`tb_lote_entrada` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almoxarifadoWeb`.`tb_lote_saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifadoWeb`.`tb_lote_saida` (
  `codigo` INT NOT NULL auto_increment,
  `quantidade` VARCHAR(45) NULL,
  `tb_funcionario_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_tb_lote_saida_tb_funcionario1_idx` (`tb_funcionario_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_lote_saida_tb_funcionario1`
    FOREIGN KEY (`tb_funcionario_codigo`)
    REFERENCES `almoxarifadoWeb`.`tb_funcionario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almoxarifadoWeb`.`tb_item_saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifadoWeb`.`tb_item_saida` (
  `codigo` INT NOT NULL auto_increment,
  `quantidade` INT NULL,
  `tb_produto_codigo` INT NOT NULL,
  `tb_lote_saida_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `tb_lote_saida_codigo`),
  INDEX `fk_tb_item_saida_tb_produto1_idx` (`tb_produto_codigo` ASC) VISIBLE,
  INDEX `fk_tb_item_saida_tb_lote_saida1_idx` (`tb_lote_saida_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_item_saida_tb_produto1`
    FOREIGN KEY (`tb_produto_codigo`)
    REFERENCES `almoxarifadoWeb`.`tb_produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_item_saida_tb_lote_saida1`
    FOREIGN KEY (`tb_lote_saida_codigo`)
    REFERENCES `almoxarifadoWeb`.`tb_lote_saida` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
