-- mysql script generated by mysql workbench
-- mon oct 12 09:42:42 2020
-- model: new model    version: 1.0
-- mysql workbench forward engineering

set @old_unique_checks=@@unique_checks, unique_checks=0;
set @old_foreign_key_checks=@@foreign_key_checks, foreign_key_checks=0;
set @old_sql_mode=@@sql_mode, sql_mode='only_full_group_by,strict_trans_tables,no_zero_in_date,no_zero_date,error_for_division_by_zero,no_engine_substitution';

-- -----------------------------------------------------
-- schema almoxarifadoweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- schema almoxarifadoweb
-- -----------------------------------------------------
create schema if not exists `almoxarifadoweb` default character set utf8 ;
use `almoxarifadoweb` ;

-- -----------------------------------------------------
-- table `almoxarifadoweb`.`tb_produto`
-- -----------------------------------------------------
create table if not exists `almoxarifadoweb`.`tb_produto` (
  `codigo` int not null AUTO_INCREMENT,
  `nome` varchar(45) null,
  `marca` varchar(45) null,
  `categoria` varchar(45) null,
  `descricao` varchar(100) null,
  primary key (`codigo`))
engine = innodb;


-- -----------------------------------------------------
-- table `almoxarifadoweb`.`tb_lote_entrada`
-- -----------------------------------------------------
create table if not exists `almoxarifadoweb`.`tb_lote_entrada` (
  `codigo` int not null AUTO_INCREMENT,
  `dataEntrada` date null,
  primary key (`codigo`))
engine = innodb;


-- -----------------------------------------------------
-- table `almoxarifadoweb`.`tb_item_entrada`
-- -----------------------------------------------------
create table if not exists `almoxarifadoweb`.`tb_item_entrada` (
  `codigo` int not null AUTO_INCREMENT,
  `quantidade` int null,
  `tb_produto_codigo` int not null,
  `tb_lote_entrada_codigo` int not null,
  primary key (`codigo`, `tb_lote_entrada_codigo`),
  index `fk_itementrada_produto_idx` (`tb_produto_codigo` asc) visible,
  index `fk_itementrada_loteentrada1_idx` (`tb_lote_entrada_codigo` asc) visible,
  constraint `fk_itementrada_produto`
    foreign key (`tb_produto_codigo`)
    references `almoxarifadoweb`.`tb_produto` (`codigo`)
    on delete no action
    on update no action,
  constraint `fk_itementrada_loteentrada1`
    foreign key (`tb_lote_entrada_codigo`)
    references `almoxarifadoweb`.`tb_lote_entrada` (`codigo`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `almoxarifadoweb`.`tb_item_estoque`
-- -----------------------------------------------------
create table if not exists `almoxarifadoweb`.`tb_item_estoque` (
  `codigo` int not null AUTO_INCREMENT,
  `quantidade` int null,
  `tb_produto_codigo` int not null,
  primary key (`codigo`),
  index `fk_itemestoque_produto1_idx` (`tb_produto_codigo` asc) visible,
  constraint `fk_itemestoque_produto1`
    foreign key (`tb_produto_codigo`)
    references `almoxarifadoweb`.`tb_produto` (`codigo`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `almoxarifadoweb`.`tb_funcionario`
-- -----------------------------------------------------
create table if not exists `almoxarifadoweb`.`tb_funcionario` (
  `codigo` int not null AUTO_INCREMENT,
  `nome` varchar(45) null,
  `departamento` varchar(45) null,
  primary key (`codigo`))
engine = innodb;


-- -----------------------------------------------------
-- table `almoxarifadoweb`.`tb_lote_saida`
-- -----------------------------------------------------
create table if not exists `almoxarifadoweb`.`tb_lote_saida` (
  `codigo` int not null AUTO_INCREMENT,
  `dataSaida` date null,
  `tb_funcionario_codigo` int not null,
  primary key (`codigo`),
  index `fk_lotesaida_funcionario1_idx` (`tb_funcionario_codigo` asc) visible,
  constraint `fk_lotesaida_funcionario1`
    foreign key (`tb_funcionario_codigo`)
    references `almoxarifadoweb`.`tb_funcionario` (`codigo`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `almoxarifadoweb`.`tb_itemsaida`
-- -----------------------------------------------------
create table if not exists `almoxarifadoweb`.`tb_item_saida` (
  `codigo` int not null AUTO_INCREMENT,
  `quantidade` int null,
  `tb_produto_codigo` int not null,
  `tb_lote_saida_codigo` int not null,
  primary key (`codigo`, `tb_lote_saida_codigo`),
  index `fk_itemsaida_produto1_idx` (`tb_produto_codigo` asc) visible,
  index `fk_itemsaida_lotesaida1_idx` (`tb_lote_saida_codigo` asc) visible,
  constraint `fk_itemsaida_produto1`
    foreign key (`tb_produto_codigo`)
    references `almoxarifadoweb`.`tb_produto` (`codigo`)
    on delete no action
    on update no action,
  constraint `fk_itemsaida_lotesaida1`
    foreign key (`tb_lote_saida_codigo`)
    references `almoxarifadoweb`.`tb_lote_saida` (`codigo`)
    on delete no action
    on update no action)
engine = innodb;


set sql_mode=@old_sql_mode;
set foreign_key_checks=@old_foreign_key_checks;
set unique_checks=@old_unique_checks;
